### ISSUE TITLE
Uncaught exception 'OdfException' with message 'Invalid image'

### ISSUE THREAD

**Issue by zakymujayin** [cybermonde/odtphp#32]
`Fatal error: Uncaught exception 'OdfException' with message 'Invalid image' in /var/www/html/simponie/backend/system/plugins/odtPHP/odf.php:137 Stack trace: #0 /var/www/html/simponie/backend/www/modules/pelayanan/controllers/verifikasi.php(2727): Odf->setImage('f_foto', './fm/test/ttd-4...') #1 [internal function]: Verifikasi->print_sk('4195') #2 /var/www/html/simponie/backend/system/codeigniter/CodeIgniter.php(236): call_user_func_array(Array, Array) #3 /var/www/html/simponie/backend/index.php(129): require_once('/var/www/html/s...') #4 {main} thrown in /var/www/html/simponie/backend/system/plugins/odtPHP/odf.php on line 13

i'm stuck, please help me how to fix this problem 😖 
THANKS

**Comment by james2001** [comment]
What is the value of `getimagesize(''./fm/test/ttd-4...');` ?

**Comment by zakymujayin** [comment]
value of getimagesize(''./fm/test/ttd-4...'); is a link to get foto.
